### ISSUE TITLE
Deprecation warning on encrypt and encryption_version

### ISSUE THREAD

**Issue by miguelcnf** [chef/cheffish#95]
```
Deprecated features used!
  encrypt nil currently does not overwrite the value of encrypt. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :encrypt, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.5.0/lib/chef/provider/chef_data_bag_item.rb:115:in `load_current_resource'
  encryption_version nil currently does not overwrite the value of encryption_version. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :encryption_version, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.5.0/lib/chef/provider/chef_data_bag_item.rb:116:in `load_current_resource'
```

Just documenting a dep warning I'm seeing.
Versions can be seen in the output.

**Comment by thommay** [comment]
This was fixed by #107
